# azure pipelines build and test PyMAPDL Reader

variables:
  ALLOW_PLOTTING: true
  package_name: ansys-mapdl-reader
  SHELLOPTS: 'errexit:pipefail'


trigger:
  branches:
    include:
    - '*'
    exclude:
    - gh-pages
  tags:
    include:
    - '*'

jobs:
- job: Linux
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    DISPLAY: ':99.0'
    PYVISTA_OFF_SCREEN: 'True'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'
    - script: |
        set -ex
        docker pull quay.io/pypa/manylinux2010_x86_64
        docker run -e package_name=$(package_name) --rm -v `pwd`:/io quay.io/pypa/manylinux2010_x86_64 /io/.ci/build_wheels.sh $(python.version)
      displayName: Build wheels using manylinux2010
    - script: |
        .ci/setup_headless_display.sh
    - template: .ci/install_package.yml
    - template: .ci/unit_testing.yml
    - template: .ci/azure-publish-dist.yml


- job: Windows
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(python.version)
        addToPath: true
    - powershell: |
        powershell .ci/install_opengl.ps1
      displayName: 'Install OpenGL'
    - template: .ci/build_wheel.yml
    - template: .ci/install_package.yml
    - template: .ci/unit_testing.yml
    - template: .ci/azure-publish-dist.yml


- job: macOS
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  pool:
    vmImage: 'macOS-10.15'
  steps:
    - script: .ci/macos-install-python.sh '$(python.version)'
      displayName: Install Python
    - template: .ci/build_wheel.yml
    - template: .ci/install_package.yml
    - template: .ci/unit_testing_allow_error.yml
    - template: .ci/azure-publish-dist.yml