name: Dependabot and pre-commit.ci auto-merge
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Only run this workflow for branches starting with "dependabot/" or "pre-commit-ci-update-config"
    if: |
      startsWith(github.head_ref, 'dependabot/') ||
      startsWith(github.head_ref, 'pre-commit-ci-update-config')
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
