# Build documentation
name: Documentation Build

on: [push, pull_request, workflow_dispatch]

jobs:
  docs_build:
    runs-on: ubuntu-20.04

    env:
      DISPLAY: ':99.0'
      PYANSYS_OFF_SCREEN: True

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8

      - name: Install, start, and test the virtual framebuffer
        run: |
          .ci/setup_headless_display.sh
          pip install -r .ci/requirements_test_xvfb.txt --disable-pip-version-check
          python .ci/display_test.py

      - name: Install ansys-mapdl-reader
        run: |
          pip install -r requirements_build.txt --disable-pip-version-check
          python setup.py bdist_wheel
          pip install dist/ansys*.whl --disable-pip-version-check
          cd tests/
          python -c "from ansys.mapdl import reader as pymapdl_reader; print(pymapdl_reader.Report())"
  
      - name: Build Documentation
        run: |
          sudo apt install pandoc -qy
          pip install -r requirements_docs.txt --disable-pip-version-check
          make -C doc html
  
      - name: Upload Documentation
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Documentation
          path: doc/build/html
          retention-days: 7

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/build/html
          CLEAN: true